server:
  port: '@server.port@'
  rest:
    port: '@server.rest.port@'

management:
  security:
    flag: false
  server:
    port: '@management.port@'
  metrics:
    export:
      statsd:
        flavor: etsy
        enabled: false
      prometheus:
        enabled: false
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

spring:
  application:
    name: '@project.name@'
  output:
    ansi:
      enabled: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        default_schema: org_manager
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://changeit:5432/org_manager
    username: changeit
    password: changeit
  flyway:
    table: schema_version
    schemas: org_manager
    url: jdbc:postgresql://changeit:5432/org_manager
    user: changeit
    password: changeit

hibernate:
  physical_naming_strategy: com.rbkmoney.orgmanager.entity.naming.SnakeCaseNamingStrategy

info:
  version: '@project.version@'
  stage: dev

keycloak:
  realm: internal
  auth-server-url: http://keycloak:8080/auth
  resource: common-api
  not-before: 0
  ssl-required: none
  realm-public-key-file-path:
  realm-public-key:

auth.enabled: true

invite-token:
  lifetime-in-days: 30

scheduler:
  invitation:
    enabled: false
    lockFor: 30m
    checkStatusDelay: 10000

dudoser:
  url: http://dudoser:8022/dudos
  networkTimeout: 10000

dashboard:
  url: https://dashboard.rbk.money/organization-section/accept-invitation

bouncer:
  url: http://localhost:8022/change_it
  networkTimeout: 10000
  context-fragment-id: orgmgmt
  deployment-id: production
  auth-method: SessionToken
  realm: external
  rule-set-id: change_it

access-check:
  enabled: false
