ALTER TABLE org_manager.invitation
    ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS accepted_member_id VARCHAR
